// News

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const CLEAR_NEWS = 'CLEAR_NEWS';


// Chars

export const GET_CHARS_SUCCESS = 'GET_CHARS_SUCCESS';
export const CLEAR_CHARS = 'CLEAR_CHARS';


// SERIES

export const GET_SERIES_SUCCESS = 'GET_SERIES_SUCCESS';
export const CLEAR_SERIES = 'CLEAR_SERIES';

// ORGANIZATIONS

export const GET_ORGANIZATIONS_SUCCESS = 'GET_ORGANIZATIONS_SUCCESS';
export const CLEAR_ORGANIZATIONS = 'CLEAR_ORGANIZATIONS';

