// News

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const CLEAR_NEWS = 'CLEAR_NEWS';


// Chars

export const GET_CHARS_SUCCESS = 'GET_CHARS_SUCCESS';


// SERIES

export const GET_SERIES_SUCCESS = 'GET_SERIES_SUCCESS';

// ORGANIZATIONS

export const GET_ORGANIZATIONS_SUCCESS = 'GET_ORGANIZATIONS_SUCCESS';

